@url = http://localhost:3001/api/persons/
@endpoint = http://localhost:3001/api/persons/

GET {{url}} 

###

GET {{endpoint}}4
###

POST {{url}}
content-type: application/json

{
    "name": "Agbako", 
    "number": "443456"
}

### 
PATCH {{url}}2
Content-Type: application/json

{

    "number": "70442928932"

}