@url = http://localhost:3030/api/persons/
@endpoint = http://localhost:3030/api/persons/

GET {{url}} 

###

GET {{endpoint}}4
###

POST {{url}}
content-type: application/json

{
    "name": "Agbaran", 
    "number": "664453"
}

### 
PATCH {{url}}2
Content-Type: application/json

{

    "number": "70442928932"

}

### 

DELETE {{url}}2
